# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a30d5604ae6d71ecc557f0bdfc620f3e3d727c1186160b8daa3ed25cf403f614999b5040fe9b289af1af954ed2f11099f9c8e8ad4a562bc53a0db7ca2f21034

test:
  secret_key_base: 91b23c4522c16a52b9288196753dbd8d703e4a3c622f583e9813dc7178dcf0e900ea2b31cf6537aef705d13d699c90f3a9dcf7058634cd95d6f89f3ceb3d68cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
